### ISSUE TITLE
deprecated minimatch@2.0.10

### ISSUE THREAD

**Issue by simwin** [Project-OSRM/osrm-frontend-v2#205] opened 2016-12-05 14:50 UTC
when I try npm install:
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
How can I fix it?

**Comment by danpat** [comment] 2016-12-05 19:45
@simwin It's just a warning - feel free to submit a patch that updates `package.json` to a newer version.

**Comment by perliedman** [comment] 2016-12-06 13:31
I think the problem is that osrm-frontend doesn't depend on minimatch itself, it's a dependency somewhere one or more levels down the dependency tree.

So, the fix would be to either upgrade any packages depending on this particular version of minimatch, or make those project update _their_ dependencies.

**Comment by yuryleb** [comment] 2017-04-19 13:06
Issue could be closed due to merged #238

**Closed as completed** 2017-04-19 15:09 UTC
