### ISSUE TITLE
Can't set BACKEND env var

### ISSUE THREAD

**Issue by pocman** [Project-OSRM/osrm-frontend-v2#236] opened 2017-04-14 15:04 UTC
Hi, 
I'm trying to override the Backend env var as specified in the README `-e BACKEND='http://localhost:5001'` but nothing changed in the browser. 
I still have `:5000/route/v1/driving/2.3514992,48.8566101;2.3200035095214844,48.88266670851026?overview=false&alternatives=true&steps=true&hints=; Failed to load resource: net::ERR_CONNECTION_REFUSED`

**Comment by daniel-j-h** [comment] 2017-04-14 16:51
Ha yes I see what you mean. The problem is although we are accepting a env variable we already write the env BACKEND variable into our files at image build time:

https://github.com/Project-OSRM/osrm-frontend/blob/ebd652d2396c0caaaaa4870a6e72c7cf89045fc5/docker/Dockerfile#L9-L13

You have two options here:
- Derive your own image and change the BACKEND at docker build time
- Change how we replace the paths in the source with the BACKEND variable at docker run time (I would prefer this option, and to have it upstream). For this you need to remove replacing the paths at docker build time (in the RUN command) and do it e.g. in the npm start step.

**Comment by danpat** [comment] 2017-04-17 22:55
@pocman Can you give https://github.com/Project-OSRM/osrm-frontend/pull/237  a go and see if it fixes the problem for you?  I implemented the "replace at runtime" approach suggested by @daniel-j-h

**Comment by pocman** [comment] 2017-04-19 07:38
Working great. Thanks

**Comment by daniel-j-h** [comment] 2017-05-19 13:35
This landed with https://github.com/Project-OSRM/osrm-frontend/pull/237.

**Closed as completed by daniel-j-h** 2017-05-19 13:35 UTC
Labels: bug
